name: Bug report
description: Report a broken or unexpected behaviour
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill in as much detail as you can.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug and what you expected to happen instead.
      placeholder: |
        I ran `the-data-packet --script-only` and expected a script file to be written to ./output,
        but instead I got a KeyError: 'content' traceback.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Exact commands or code needed to trigger the bug.
      placeholder: |
        1. docker run ... --script-only
        2. ...
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error output or logs
      description: Paste the full error message, stack trace, or relevant log lines.
      render: text

  - type: dropdown
    id: run_method
    attributes:
      label: How are you running The Data Packet?
      options:
        - Docker (GHCR image)
        - Docker (locally built)
        - Python package (pip / hatch)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `the-data-packet --version` or the Docker image tag.
      placeholder: "e.g. 2.0.0 / latest"
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python version
      description: Omit if running via Docker.
      placeholder: "e.g. 3.11.4"

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "e.g. Ubuntu 24.04 / macOS 15 / Windows 11"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other information that might help (config flags used, cloud provider, etc.).
